### ISSUE TITLE
jest-progress-bar-reporter overwrite the verbose configration

### ISSUE THREAD

**Issue by xiqwertyui** [pierreroth64/jest-progress-bar-reporter#13]
This is my jest cofigure js:
  module.exports = {
      preset: 'ts-jest',
      testEnvironment: 'node',
      maxWorkers: 1,
      verbose: true,
      reporters: ['jest-progress-bar-reporter'], 
  };  
![image](https://user-images.githubusercontent.com/61354982/201365155-2145d42c-9709-4091-aaa6-19aeb92fd3e8.png)
Even the verbose is set to verbose: ture. It doesn't show any detail about the test message.
Normally it should be like this:
![image](https://user-images.githubusercontent.com/61354982/201365454-7b11401f-ad33-4553-8e3c-387c96edcc50.png)

But thanks for this powerful tool, it really makes testing less painful!

**Comment by radfahrer** [comment]
This is default jest behavior as noted in their docs: https://jestjs.io/docs/configuration#default-reporter

You might want to run both this reporter and the summary reporter:

```js 
reporters: ['jest-progress-bar-reporter', 'summary']
```
